term_launch = "alacritty -e"

[battery]
icons = "î‚°ï‰„î‚±ï‰ƒï‰‚ï‰ï‰€"
charging = "ï¶"
alert = 10

[temperature]
icons = "ï‹‹ï‹Šï‹‰ï‹ˆï‹‡"
alert = "ï©ï±"
min = 45
max = 75
path = "/sys/class/thermal/thermal_zone0/temp"
interval = 1000

[memory]
icon = "ï”¸"
alert = 80
interval = 1000

[cpu]
icon = "ï‹›"
alert = 90
interval = 1000

[brightness]
icon = "îƒ‰"

[network]
icons = "ïšªïš«ï‡«"
disabled = "ïš¬"
interface = "wlan0"

[volume]
icons = "ï€¦ï€§ïš¨ï€¨"
bluetooth = "ïŠ”"
muted = "ï‹¢"
silent = "ïš©"
alert = "ï€¨ï±"
mic = "ï„°"

[scratchpad]
icon = "î‘¿"

[workspaces]
'default' = "ï„‘"

[workspaces.icons]
'1' = "ïš­"
'2' = "ï£¶"
'3' = "ï£µ"
'4' = "ïƒ§"
'5' = "ïˆ"
'6' = "ï†“"
'7' = "ï’»"
'8' = "ï †"
'9' = "ï’"
'10' = "ïœ "
'11' = "ï‹œ"
'12' = "ï˜™"

[language.icons]
'English (US)' = 'ğŸ‡ºğŸ‡¸'
'Russian' = 'ğŸ‡·ğŸ‡º'

[style.paths]
scss = "/style/style.scss"
css = "/style.css"

[clock]
time = "ï€— hh:mm:ss a"
date = "ï³ eee, dd MMM yyyy"

[log]
level = 'info'
